import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const SUPABASE_URL='https://aoknkxdatjbuuqzqxgrf.supabase.co';
const SUPABASE_KEY='sb_publishable_7Fx4Y1MWj5iczA1s_lZzrg_2IdGqqTP';
const supabase=createClient(SUPABASE_URL,SUPABASE_KEY);
let session=null,profile=null,cache={initiatives:[],profiles:[],captures:[],tasks:[],approvals:[],catalogTypes:[],catalogValues:[],plans:[],kpis:[],milestones:[]};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(n||0));
const fmtDate=d=>d?new Intl.DateTimeFormat('es-EC',{dateStyle:'medium'}).format(new Date(d)): '—';
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2300)}
function badge(v){const c=v==='Validado'||v==='Aprobado'||v==='S5'||v==='Cerrada'||v==='On Track'?'green':v==='S4'?'blue':v==='S3'||String(v).includes('Pendiente')?'amber':v==='Rechazado'||v==='Risk'?'red':'gray';return `<span class="badge ${c}">${v||'—'}</span>`}
function initials(n='FP'){return n.split(' ').filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()}
function showPage(name){$$('.page').forEach(p=>p.classList.remove('active'));$(`#page-${name}`).classList.add('active');$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.page===name));const titles={dashboard:'Dashboard',initiatives:'Iniciativas',planning:'Planificación Financiera',captures:'Captura Mensual',tasks:'Pendientes',kpis:'KPI',milestones:'Hitos',approvals:'Aprobaciones',reports:'Reportes',users:'Usuarios',catalogs:'Catálogos'};$('#pageTitle').textContent=titles[name]||'FP Tracker'}
function openModal(title,body,footer=''){ $('#modalTitle').textContent=title;$('#modalBody').innerHTML=body;$('#modalFooter').innerHTML=footer;$('#modalBackdrop').classList.remove('hidden') }
function closeModal(){ $('#modalBackdrop').classList.add('hidden') }
$('#modalClose').onclick=closeModal;$('#modalBackdrop').onclick=e=>{if(e.target.id==='modalBackdrop')closeModal()};

async function loadProfile(){const {data,error}=await supabase.from('fp_profiles').select('*').eq('user_id',session.user.id).single();if(error)throw new Error('Tu cuenta existe, pero todavía no tiene perfil habilitado en FP Tracker.');profile=data;$('#userName').textContent=profile.full_name;$('#userRole').textContent=profile.role;$('#userInitials').textContent=initials(profile.full_name);$$('[data-roles]').forEach(el=>el.classList.toggle('hidden',!el.dataset.roles.split('|').includes(profile.role)));$$('.nav-group').forEach(g=>{const visible=[...g.querySelectorAll('.nav')].some(n=>!n.classList.contains('hidden'));g.classList.toggle('hidden',!visible)})}
async function loadData(){const [i,p,c,t,a,ct,cv,pl,k,m]=await Promise.all([
 supabase.from('fp_initiatives').select('*').order('created_at',{ascending:false}),
 supabase.from('fp_profiles').select('*').order('full_name'),
 supabase.from('fp_monthly_captures').select('*').order('period',{ascending:false}),
 supabase.from('fp_tasks').select('*').order('created_at',{ascending:false}),
 supabase.from('fp_approvals').select('*').order('requested_at',{ascending:false}),
 supabase.from('fp_catalog_types').select('*').eq('active',true).order('sort_order'),
 supabase.from('fp_catalog_values').select('*').eq('active',true).order('sort_order'),
 supabase.from('fp_monthly_plans').select('*').order('period'),
 supabase.from('fp_kpis').select('*'),
 supabase.from('fp_milestones').select('*')]);
 for(const r of [i,p,c,t,a,ct,cv,pl,k,m])if(r.error)throw r.error;
 cache={initiatives:i.data,profiles:p.data,captures:c.data,tasks:t.data,approvals:a.data,catalogTypes:ct.data,catalogValues:cv.data,plans:pl.data,kpis:k.data,milestones:m.data};renderAll()}
const person=id=>cache.profiles.find(p=>p.user_id===id)?.full_name||'—';const init=id=>cache.initiatives.find(i=>i.id===id);
function renderAll(){renderDashboard();renderInitiatives();renderCaptures();renderTasks();renderApprovals();renderUsers();renderCatalogs();renderPlans();renderKpis();renderMilestones();renderReports()}
function renderDashboard(){const active=cache.initiatives.filter(i=>i.stage!=='Cerrada').length;const pending=cache.approvals.filter(a=>a.status==='Pendiente').length;const validated=cache.captures.filter(c=>c.status==='Validado');const myTasks=cache.tasks.filter(t=>t.assignee_id===profile.user_id&&t.status!=='Completado').length;$('#kpiActive').textContent=active;$('#kpiApprovals').textContent=pending;$('#kpiEbitda').textContent=money(validated.reduce((s,c)=>s+Number(c.ebitda_real||0),0));$('#kpiTasks').textContent=myTasks;$('#recentActivity').innerHTML=cache.approvals.slice(0,5).map(a=>`<div class="activity"><strong>${a.stage} · ${init(a.initiative_id)?.local_code||''} ${init(a.initiative_id)?.name||''}</strong><small>${a.status} · ${fmtDate(a.requested_at)}</small></div>`).join('')||'<small>No hay actividad todavía.</small>'}
function renderInitiatives(){$('#initiativesBody').innerHTML=cache.initiatives.map(i=>`<tr><td>${i.local_code}</td><td>${i.wave_id||'—'}</td><td><strong>${i.name}</strong></td><td>${i.country||'—'}</td><td>${i.accountable_workstream||'—'}</td><td>${person(i.owner_id)}</td><td>${badge(i.stage)}</td><td>${badge(i.weekly_status)}</td><td><button class="btn ghost initiative-action" data-id="${i.id}">Acciones</button></td></tr>`).join('')||'<tr><td colspan="9">No existen iniciativas. Crea la primera.</td></tr>';$$('.initiative-action').forEach(b=>b.onclick=()=>initiativeActions(b.dataset.id))}
function renderCaptures(){$('#capturesBody').innerHTML=cache.captures.map(c=>{const i=init(c.initiative_id);return `<tr><td>${i?.local_code||''} · ${i?.name||''}</td><td>${String(c.period).slice(0,7)}</td><td>${money(c.ebitda_real)}</td><td>${money(c.vnf_real)}</td><td>${badge(c.status)}</td><td>${person(c.validated_by)}</td><td><button class="btn ghost capture-action" data-id="${c.id}">Revisar</button></td></tr>`}).join('')||'<tr><td colspan="7">No hay capturas mensuales.</td></tr>';$$('.capture-action').forEach(b=>b.onclick=()=>captureActions(b.dataset.id))}
function renderTasks(){for(const [id,status] of [['todoTasks','Por hacer'],['doingTasks','En curso'],['doneTasks','Completado']]){$('#'+id).innerHTML=cache.tasks.filter(t=>t.status===status).map(t=>`<article class="task-card"><strong>${t.title}</strong><p>${init(t.initiative_id)?.local_code||''} · ${person(t.assignee_id)}</p><p>Vence: ${t.due_date||'Sin fecha'}</p>${status!=='Completado'&& (t.assignee_id===profile.user_id||['Administrador','Key User','OT','Finanzas'].includes(profile.role))?`<button class="btn ghost task-complete" data-id="${t.id}">Completar</button>`:''}</article>`).join('')||'<small>Sin registros</small>'}$$('.task-complete').forEach(b=>b.onclick=()=>completeTask(b.dataset.id))}
function renderApprovals(){$('#approvalsBody').innerHTML=cache.approvals.map(a=>{const i=init(a.initiative_id);return `<tr><td>${a.stage}</td><td>${i?.local_code||''} · ${i?.name||''}</td><td>${a.capture_id?'Captura mensual':a.stage==='S5'?'Cierre':'Iniciativa / planificación'}</td><td>${badge(a.status)}</td><td>${fmtDate(a.requested_at)}</td><td>${a.status==='Pendiente'?`<button class="btn ghost approval-action" data-id="${a.id}">Revisar</button>`:'—'}</td></tr>`}).join('')||'<tr><td colspan="6">No hay aprobaciones.</td></tr>';$$('.approval-action').forEach(b=>b.onclick=()=>approvalAction(b.dataset.id))}
function renderUsers(){$('#usersBody').innerHTML=cache.profiles.map(p=>`<tr><td>${p.hcm_code||'—'}</td><td>${p.full_name}</td><td>${p.email}</td><td>${p.role}</td><td>${p.country||'—'}</td><td>${badge(p.active?'Activo':'Inactivo')}</td></tr>`).join('')}
function renderCatalogs(){$('#catalogsGrid').innerHTML=cache.catalogTypes.map(t=>{const vals=cache.catalogValues.filter(v=>v.catalog_type_id===t.id);return `<article class="card catalog-card"><strong>${t.name}</strong><p>${vals.length} valores activos</p><small>${vals.slice(0,4).map(v=>v.name).join(' · ')||'Sin valores'}</small></article>`}).join('')}
function renderPlans(){$('#planningContent').innerHTML=`<table><thead><tr><th>Iniciativa</th><th>Periodo</th><th>EBITDA Forecast</th><th>EBITDA Objetivo</th><th>VNF Forecast</th><th>VNF Objetivo</th><th>Versión</th><th>Estado</th></tr></thead><tbody>${cache.plans.map(p=>`<tr><td>${init(p.initiative_id)?.local_code||''}</td><td>${String(p.period).slice(0,7)}</td><td>${money(p.ebitda_forecast)}</td><td>${money(p.ebitda_target)}</td><td>${money(p.vnf_forecast)}</td><td>${money(p.vnf_target)}</td><td>v${p.version}</td><td>${badge(p.status)}</td></tr>`).join('')||'<tr><td colspan="8">Sin planificación.</td></tr>'}</tbody></table>`}
function renderKpis(){$('#kpisContent').innerHTML=`<table><thead><tr><th>Iniciativa</th><th>KPI</th><th>Tipo</th><th>Meta</th><th>Valor</th><th>Unidad</th></tr></thead><tbody>${cache.kpis.map(k=>`<tr><td>${init(k.initiative_id)?.local_code||''}</td><td>${k.name}</td><td>${k.kpi_type||'—'}</td><td>${k.target??'—'}</td><td>${k.value??'—'}</td><td>${k.unit||'—'}</td></tr>`).join('')||'<tr><td colspan="6">Sin KPI.</td></tr>'}</tbody></table>`}
function renderMilestones(){$('#milestonesContent').innerHTML=`<table><thead><tr><th>Iniciativa</th><th>Hito</th><th>Responsable</th><th>Plan</th><th>Real</th><th>Estado</th></tr></thead><tbody>${cache.milestones.map(m=>`<tr><td>${init(m.initiative_id)?.local_code||''}</td><td>${m.name}</td><td>${person(m.owner_id)}</td><td>${m.planned_date||'—'}</td><td>${m.actual_date||'—'}</td><td>${badge(m.status)}</td></tr>`).join('')||'<tr><td colspan="6">Sin hitos.</td></tr>'}</tbody></table>`}
function renderReports(){const v=cache.captures.filter(c=>c.status==='Validado');$('#reportEbitda').textContent=money(v.reduce((s,c)=>s+Number(c.ebitda_real||0),0));$('#reportVnf').textContent=money(v.reduce((s,c)=>s+Number(c.vnf_real||0),0));$('#reportCaptures').textContent=v.length}

function options(type,selected=''){const t=cache.catalogTypes.find(x=>x.code===type);return cache.catalogValues.filter(v=>v.catalog_type_id===t?.id).map(v=>`<option ${v.name===selected?'selected':''}>${v.name}</option>`).join('')}
$('#newInitiativeBtn').onclick=()=>{openModal('Nueva iniciativa',`<div class="form-grid"><label class="span2">Nombre *<input id="fName"></label><label>País *<select id="fCountry">${options('country')}</select></label><label>Global Lever<select id="fLever">${options('global_lever')}</select></label><label>Accountable Workstream<select id="fWs">${options('accountable_workstream')}</select></label><label>Functional Area<select id="fArea">${options('functional_area')}</select></label><label>Initiative Type<select id="fType">${options('initiative_type')}</select></label><label>Responsable<select id="fOwner">${cache.profiles.filter(p=>p.active).map(p=>`<option value="${p.user_id}">${p.full_name}</option>`).join('')}</select></label><label>Backup<select id="fBackup"><option value="">Sin backup</option>${cache.profiles.filter(p=>p.active).map(p=>`<option value="${p.user_id}">${p.full_name}</option>`).join('')}</select></label><label>ID Wave<input id="fWave" placeholder="Opcional"></label><label class="span3">Descripción<textarea id="fDesc" rows="3"></textarea></label></div>`,`<button class="btn secondary" id="cancelModal">Cancelar</button><button class="btn primary" id="saveInitiative">Guardar borrador</button>`);$('#cancelModal').onclick=closeModal;$('#saveInitiative').onclick=createInitiative};
async function createInitiative(){const name=$('#fName').value.trim();if(!name)return toast('Ingresa el nombre de la iniciativa');const {error}=await supabase.from('fp_initiatives').insert({name,description:$('#fDesc').value,country:$('#fCountry').value,global_lever:$('#fLever').value,accountable_workstream:$('#fWs').value,functional_area:$('#fArea').value,initiative_type:$('#fType').value,owner_id:$('#fOwner').value,backup_id:$('#fBackup').value||null,wave_id:$('#fWave').value||null,created_by:profile.user_id});if(error)return toast(error.message);closeModal();toast('Borrador creado');await loadData()}
function initiativeActions(id){const i=init(id);const own=i.owner_id===profile.user_id||i.backup_id===profile.user_id;let buttons='';if(i.stage==='Borrador'&&(own||['Administrador','Key User'].includes(profile.role)))buttons+=`<button class="btn primary wf" data-action="submit_s0">Enviar a S0</button>`;if(i.stage==='S0'&&['Administrador','Key User','OT'].includes(profile.role))buttons+=`<button class="btn danger wf" data-action="reject_s0">Rechazar</button><button class="btn success wf" data-action="approve_s0">Aprobar S0</button>`;if(i.stage==='S3'&&['Administrador','Key User','Finanzas'].includes(profile.role))buttons+=`<button class="btn danger wf" data-action="reject_s3">Rechazar</button><button class="btn success wf" data-action="approve_s3">Aprobar S3</button>`;if(i.stage==='S4'&&(own||['Administrador','Key User'].includes(profile.role)))buttons+=`<button class="btn primary wf" data-action="request_close">Solicitar cierre S5</button>`;if(i.stage==='S5'&&['Administrador','Key User','OT','Finanzas'].includes(profile.role))buttons+=`<button class="btn danger wf" data-action="reject_close">Rechazar cierre</button><button class="btn success wf" data-action="approve_close">Aprobar cierre</button>`;openModal(`${i.local_code} · ${i.name}`,`<div class="notice">Etapa actual: <strong>${i.stage}</strong></div><div class="form-grid"><label class="span3">Comentario<textarea id="wfComment" rows="3" placeholder="Comentario u observación"></textarea></label></div>`,buttons||'<button class="btn secondary" id="cancelModal">Cerrar</button>');$('#cancelModal')&&($('#cancelModal').onclick=closeModal);$$('.wf').forEach(b=>b.onclick=()=>workflow(b.dataset.action,{initiative_id:id,comment:$('#wfComment').value}))}
async function workflow(action,payload){const {data,error}=await supabase.functions.invoke('fp-workflow',{body:{action,...payload}});if(error||data?.error)return toast(data?.error||error.message);closeModal();toast('Workflow actualizado');await loadData()}

$('#newCaptureBtn').onclick=()=>{const eligible=cache.initiatives.filter(i=>i.stage==='S4'&&(['Administrador','Key User','Finanzas'].includes(profile.role)||i.owner_id===profile.user_id||i.backup_id===profile.user_id));openModal('Nueva captura mensual',`<div class="form-grid"><label class="span2">Iniciativa<select id="cInit">${eligible.map(i=>`<option value="${i.id}">${i.local_code} · ${i.name}</option>`).join('')}</select></label><label>Periodo<input id="cPeriod" type="month"></label><label>EBITDA Real<input id="cEbitda" type="number" step="0.01"></label><label>VNF Real<input id="cVnf" type="number" step="0.01"></label><label class="span3">Evidencias<input id="cFiles" type="file" multiple accept=".pdf,.png,.jpg,.jpeg,.xls,.xlsx"></label></div>`,`<button class="btn secondary" id="cancelModal">Cancelar</button><button class="btn primary" id="saveCapture">Guardar borrador</button>`);$('#cancelModal').onclick=closeModal;$('#saveCapture').onclick=createCapture};
async function createCapture(){if(!$('#cInit').value||!$('#cPeriod').value)return toast('Selecciona iniciativa y periodo');const period=$('#cPeriod').value+'-01';const {data,error}=await supabase.from('fp_monthly_captures').insert({initiative_id:$('#cInit').value,period,ebitda_real:Number($('#cEbitda').value||0),vnf_real:Number($('#cVnf').value||0),submitted_by:profile.user_id}).select().single();if(error)return toast(error.message);for(const file of $('#cFiles').files){const path=`${data.initiative_id}/${data.id}/${Date.now()}-${file.name}`;const up=await supabase.storage.from('fp-evidence').upload(path,file);if(!up.error)await supabase.from('fp_evidence').insert({capture_id:data.id,file_name:file.name,storage_path:path,mime_type:file.type,file_size:file.size,uploaded_by:profile.user_id})}closeModal();toast('Captura guardada');await loadData()}
function captureActions(id){const c=cache.captures.find(x=>x.id===id);const i=init(c.initiative_id);let buttons='';const own=i?.owner_id===profile.user_id||i?.backup_id===profile.user_id;if(['Borrador','Rechazado','Reabierto'].includes(c.status)&&(own||['Administrador','Key User','Finanzas'].includes(profile.role)))buttons+=`<button class="btn primary cap-wf" data-action="submit_capture">Enviar a Finanzas</button>`;if(c.status==='Pendiente Finanzas'&&['Administrador','Key User','Finanzas'].includes(profile.role))buttons+=`<button class="btn danger cap-wf" data-action="reject_capture">Rechazar</button><button class="btn success cap-wf" data-action="validate_capture">Validar</button>`;if(c.status==='Validado'&&['Administrador','Key User','OT','Finanzas'].includes(profile.role))buttons+=`<button class="btn danger cap-wf" data-action="reopen_capture">Reabrir</button>`;openModal(`Captura ${String(c.period).slice(0,7)}`,`<div class="notice">${i?.local_code||''} · ${i?.name||''}<br>Estado: <strong>${c.status}</strong></div><div class="form-grid"><label class="span3">Comentario<textarea id="capComment" rows="3"></textarea></label></div>`,buttons||'<button class="btn secondary" id="cancelModal">Cerrar</button>');$('#cancelModal')&&($('#cancelModal').onclick=closeModal);$$('.cap-wf').forEach(b=>b.onclick=()=>workflow(b.dataset.action,{capture_id:id,comment:$('#capComment').value}))}
function approvalAction(id){const a=cache.approvals.find(x=>x.id===id);if(a.capture_id)return captureActions(a.capture_id);initiativeActions(a.initiative_id)}

$('#newTaskBtn').onclick=()=>{openModal('Nuevo pendiente',`<div class="form-grid"><label class="span2">Título<input id="tTitle"></label><label>Iniciativa<select id="tInit"><option value="">General</option>${cache.initiatives.map(i=>`<option value="${i.id}">${i.local_code}</option>`).join('')}</select></label><label>Asignar a<select id="tAssignee">${cache.profiles.filter(p=>p.active).map(p=>`<option value="${p.user_id}">${p.full_name}</option>`).join('')}</select></label><label>Vencimiento<input id="tDue" type="date"></label><label>Prioridad<select id="tPriority"><option>Baja</option><option selected>Media</option><option>Alta</option><option>Crítica</option></select></label><label class="span3">Descripción<textarea id="tDesc" rows="3"></textarea></label></div>`,`<button class="btn secondary" id="cancelModal">Cancelar</button><button class="btn primary" id="saveTask">Crear</button>`);$('#cancelModal').onclick=closeModal;$('#saveTask').onclick=createTask};
async function createTask(){if(!$('#tTitle').value.trim())return toast('Ingresa el título');const {error}=await supabase.from('fp_tasks').insert({title:$('#tTitle').value,description:$('#tDesc').value,initiative_id:$('#tInit').value||null,assignee_id:$('#tAssignee').value,due_date:$('#tDue').value||null,priority:$('#tPriority').value,created_by:profile.user_id});if(error)return toast(error.message);closeModal();toast('Pendiente creado');await loadData()}
async function completeTask(id){const {error}=await supabase.from('fp_tasks').update({status:'Completado',completed_at:new Date().toISOString()}).eq('id',id);if(error)return toast(error.message);toast('Pendiente completado');await loadData()}

$('#newUserBtn').onclick=()=>{openModal('Registrar usuario',`<div class="form-grid"><label>HCM<input id="uHcm"></label><label class="span2">Nombres *<input id="uName"></label><label class="span2">Correo *<input id="uEmail" type="email"></label><label>Rol<select id="uRole"><option>Administrador</option><option>Key User</option><option>OT</option><option>Finanzas</option><option selected>Responsable</option><option>Backup</option></select></label><label>País<select id="uCountry">${options('country')}</select></label><label class="span2">Contraseña inicial *<input id="uPassword" type="password" minlength="8"></label></div><div class="notice warning" style="margin-top:12px">La contraseña se administra mediante Supabase Auth y no se almacena en las tablas de FP Tracker.</div>`,`<button class="btn secondary" id="cancelModal">Cancelar</button><button class="btn primary" id="saveUser">Registrar usuario</button>`);$('#cancelModal').onclick=closeModal;$('#saveUser').onclick=createUser};
async function createUser(){const body={hcm_code:$('#uHcm').value||null,full_name:$('#uName').value,email:$('#uEmail').value,password:$('#uPassword').value,role:$('#uRole').value,country:$('#uCountry').value};const {data,error}=await supabase.functions.invoke('fp-create-user',{body});if(error||data?.error)return toast(data?.error||error.message);closeModal();toast('Usuario creado');await loadData()}

$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginMessage').textContent='Ingresando...';const {data,error}=await supabase.auth.signInWithPassword({email:$('#loginEmail').value.trim(),password:$('#loginPassword').value});if(error){$('#loginMessage').textContent=error.message;return}session=data.session;try{await enterApp()}catch(err){$('#loginMessage').textContent=err.message;await supabase.auth.signOut()}};
async function enterApp(){await loadProfile();$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');await loadData();showPage('dashboard')}
$('#logoutBtn').onclick=async()=>{await supabase.auth.signOut();location.reload()};$$('.nav').forEach(b=>b.onclick=()=>showPage(b.dataset.page));
const {data:{session:existing}}=await supabase.auth.getSession();if(existing){session=existing;try{await enterApp()}catch(e){await supabase.auth.signOut();$('#loginMessage').textContent=e.message}}
